//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _3B
{
    using System;
    using System.Collections.Generic;
    
    public partial class admin
    {
        public string username { get; set; }
        public string pin { get; set; }
        public string fname { get; set; }
        public string lname { get; set; }
        public Nullable<System.DateTime> hiredate { get; set; }
        public string address { get; set; }
        public string city { get; set; }
        public string state { get; set; }
        public string zip { get; set; }
        public Nullable<bool> isactive { get; set; }
    }
}
