//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _3B
{
    using System;
    using System.Collections.Generic;
    
    public partial class book
    {
        public string bookid { get; set; }
        public string title { get; set; }
        public string publisher { get; set; }
        public Nullable<short> year { get; set; }
        public Nullable<short> categoryid { get; set; }
        public Nullable<double> price { get; set; }
        public Nullable<short> minquantity { get; set; }
        public Nullable<int> quantity { get; set; }
        public Nullable<bool> deleted { get; set; }
    }
}
