//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _3B
{
    using System;
    using System.Collections.Generic;
    
    public partial class customer
    {
        public string username { get; set; }
        public string pin { get; set; }
        public string fname { get; set; }
        public string lname { get; set; }
        public string address { get; set; }
        public string city { get; set; }
        public string state { get; set; }
        public Nullable<int> zip { get; set; }
        public string creditcardtype { get; set; }
        public string creditcardnumber { get; set; }
        public string expirydate { get; set; }
        public Nullable<short> categorylastsearched { get; set; }
    }
}
