//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _3B
{
    using System;
    using System.Collections.Generic;
    
    public partial class order
    {
        public short orderid { get; set; }
        public Nullable<short> quantity { get; set; }
        public string admin { get; set; }
        public string bookid { get; set; }
    }
}
