//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _3B
{
    using System;
    using System.Collections.Generic;
    
    public partial class salesline
    {
        public int salesid { get; set; }
        public string bookid { get; set; }
        public Nullable<int> quantity { get; set; }
        public Nullable<double> price { get; set; }
    }
}
